#ifndef CONFIG_H_
#define CONFIG_H_

#define GDT_KERNEL_CODE_SEGMENT_SELECTOR 0x08
#define GDT_KERNEL_DATA_SEGMENT_SELECTOR 0x10
#define OS_IDT_TOTAL_INTERRUPTS 256
#define VGA_WIDTH 80
#define VGA_HEIGHT 25

#endif
